name: basic
dependencies:
  - jedi=0.17.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - notebook=6.0.3=py37_0
  - pip=20.0.2=py37_3
  - pip:
    - findspark==1.3.0
    - matplotlib==3.2.1
    - more-itertools==8.3.0
    - numpy==1.16.3
    - scikit-learn==0.22.2
    - scipy==1.4.1
    - pandas==1.0.3
    - pyspark==2.4.5
    - pytest==5.4.1
    - pytest-filter-subpackage==0.1
    - pytest-cov==2.10.1
    - shap==0.35.0
    - simplejson==3.17.0
    - tensorflow==2.3.0
    - xgboost==1.0.2
    - jupytext
    - jupyterlab

